-- Conversations: survive backend restarts (V1 kept them in a Python dict).
CREATE TABLE conversations (
    id          TEXT PRIMARY KEY,               -- "c_<hex>", generated by the app
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE messages (
    id               BIGSERIAL PRIMARY KEY,     -- insertion order = conversation order
    conversation_id  TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role             TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content          TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- "last N messages of conversation X" is the hot query; this index serves it.
CREATE INDEX messages_conversation_idx ON messages (conversation_id, id);

-- Long-term memory: small facts about the user, shown to the model every turn.
CREATE TABLE memories (
    id          BIGSERIAL PRIMARY KEY,
    content     TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 500),
    category    TEXT NOT NULL DEFAULT 'other'
                CHECK (category IN ('preference', 'person', 'project', 'fact', 'other')),
    -- 'pending' = JARVIS proposed it and the user hasn't approved it yet.
    status      TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'pending')),
    -- Who created it: the user explicitly, or JARVIS (needs approval).
    source      TEXT NOT NULL CHECK (source IN ('user', 'assistant')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
